### ISSUE TITLE
crop的次数对识别率的影响

### ISSUE THREAD

**Issue by wuqiangch** [tianyu0207/RTFM#12]
有以下几个问题向您请教：
1、我复现出来的ShanghaiTech结果只有96%左右，没有修改任何代码，不知道什么原因；
2、crop的次数对识别率的影响特别大，我从测试集中的10次crop中随机取出一次crop来测试，识别率降到了88%左右；
3、和其他论文比较的识别率的时候，RTFM是做过10crop来训练和测试的，但是请问其他论文也做过10次crop吗？如果没有的话，那就有失公平了。
4、在Nvidia 2080Ti的inference time=0.76s，请问这个时间是10次crop的总时间还是单次crop的时间？
5、由于RTFM采用的多尺度技术，因此对于一段视频，如果有N个16帧的clips，最好的方式是这个N个clip全部输入到网络里识别是最好的，也正如测试代码所示，clips越少识别率越低。如果视频中的的N个clips单独测试，识别率也非常低，会降到80%左右。那么在实时监控的时候，每次就应该输入32个clips才能达到可以接受的识别率，但是这种方式，会导致实时性严重下降，甚至不可用。

**Comment by tianyu0207** [comment]
> 有以下几个问题向您请教：
> 1、我复现出来的ShanghaiTech结果只有96%左右，没有修改任何代码，不知道什么原因；
> 2、crop的次数对识别率的影响特别大，我从测试集中的10次crop中随机取出一次crop来测试，识别率降到了88%左右；
> 3、和其他论文比较的识别率的时候，RTFM是做过10crop来训练和测试的，但是请问其他论文也做过10次crop吗？如果没有的话，那就有失公平了。
> 4、在Nvidia 2080Ti的inference time=0.76s，请问这个时间是10次crop的总时间还是单次crop的时间？
> 5、由于RTFM采用的多尺度技术，因此对于一段视频，如果有N个16帧的clips，最好的方式是这个N个clip全部输入到网络里识别是最好的，也正如测试代码所示，clips越少识别率越低。如果视频中的的N个clips单独测试，识别率也非常低，会降到80%左右。那么在实时监控的时候，每次就应该输入32个clips才能达到可以接受的识别率，但是这种方式，会导致实时性严重下降，甚至不可用。

 there might be some auc differences between different computers and different runs. 

In the previous papers, 'Not only Look, but also Listen: Learning Multimodal Violence Detection under Weak Supervision' and 
'Graph Convolutional Label Noise Cleaner: Train a Plug-and-play Action Classifier for Anomaly Detection'. They all use 10-crop.  Some of the other papers did not provide code. So I'm not sure with them though...

The time should be the one for single-cropped images.  For question 5, I agree that it will harm some of the efficiency of the method when use more clips as input.

**Comment by wuqiangch** [comment]
@tianyu0207  Thanks!
