### ISSUE TITLE
How is the final loss function used to find the [0,1] T dimensional vector?

### ISSUE THREAD

**Issue by GowthamGottimukkala** [tianyu0207/RTFM#14]
I have a doubt in your paper. In the section 3.4 the loss function is written as 
![image](https://user-images.githubusercontent.com/35572230/117193761-df07de80-ae00-11eb-8fbb-d1c9b78376df.png)
Here the loss function is using the output from `f` which is [0,1,1,....T times] vector and `y` which is single value video level label. I am having hard time to understand how does this log loss function work if one is of length T and the other one is a single value?

**Comment by tianyu0207** [comment]
> I have a doubt in your paper. In the section 3.4 the loss function is written as
> ![image](https://user-images.githubusercontent.com/35572230/117193761-df07de80-ae00-11eb-8fbb-d1c9b78376df.png)
> Here the loss function is using the output from `f` which is [0,1,1,....T times] vector and `y` which is single value video level label. I am having hard time to understand how does this log loss function work if one is of length T and the other one is a single value?

The loss is computed based on the top-k instances of normal and abnormal videos. The k instances from normal inherits the normal class and  that from abnormal inherits the abnormal class.
