### ISSUE TITLE
Unable to download I3D train and test files

### ISSUE THREAD

**Issue by daviduarte** [tianyu0207/RTFM#17]
The I3D files available in this repo is hosted in the Office 365, but every time my download is aborted or the files come corrupted. I tried download few individuals files separately per time, but some problems occurred again. 

There is another source of the I3D files?

**Comment by yassinesamet** [comment]
any solution ??

**Comment by daviduarte** [comment]
I tried again download small file batchs one by one. It tooks a lot of work, but I got it. I shared in GDrive:

https://drive.google.com/drive/folders/1kkKPriOG_8pm64polSS1vnwRxnHoS2ts?usp=sharing

**Comment by tianyu0207** [comment]
Sorry for the late reply. I have also uploaded the ShanghaiTech features on Google drive. Please see readme for the link.
