### ISSUE TITLE
ask for the code of data preprocessing before I3d

### ISSUE THREAD

**Issue by marsplant** [tianyu0207/RTFM#21]
thank you for your excellent work!

I saw people met the same problem of data preprocessing on the I3D feature extraction.

Can you share the code of data preprocessing before I3d ?

Can you specify exactly how you do the tenCrop on an image ?

thanks!

**Comment by tianyu0207** [comment]
> thank you for your excellent work!
> 
> I saw people met the same problem of data preprocessing on the I3D feature extraction.
> 
> Can you share the code of data preprocessing before I3d ?
> 
> Can you specify exactly how you do the tenCrop on an image ?
> 
> thanks!

Below is my feature extraction setup.

mean = [114.75, 114.75, 114.75]
std = [57.375, 57.375, 57.375]

split == '10_crop_ucf':
transform = transforms.Compose([
gtransforms.GroupResize(256),
gtransforms.GroupTenCrop(224),
gtransforms.ten_crop_ToTensor(),
gtransforms.GroupNormalize_ten_crop(mean, std),
gtransforms.LoopPad(max_len),
])

class GroupTenCrop(object):
def init(self, size):
transform = torchvision.transforms.Compose([
torchvision.transforms.TenCrop(size),
torchvision.transforms.Lambda(lambda crops: torch.stack([torchvision.transforms.ToTensor()(crop) for crop in crops])),
])
self.worker = transform
def call(self, img_group):
return [self.worker(img) for img in img_group]

class ToTensor(object):
def init(self):
self.worker = lambda x: F.to_tensor(x) * 255
def call(self, img_group):
img_group = [self.worker(img) for img in img_group]
return torch.stack(img_group, 0)

**Comment by DungVo1507** [comment]
Hi @marsplant,
I am also looking for a way to extract i3d features on my dataset. I don't know if you have succeeded in extracting i3d features or not? If successful can you guide me?
Thank you so much!

**Comment by daviduarte** [comment]
Can you release the LoopPad part?

Thank you!

**Comment by zimengxueying** [comment]
> GroupTenCrop

Sorry to bother you... Have ever solved the problem? If successful can you guide me?
Thank you so much!

**Comment by zimengxueying** [comment]
> Hi @marsplant, I am also looking for a way to extract i3d features on my dataset. I don't know if you have succeeded in extracting i3d features or not? If successful can you guide me? Thank you so much!

Sorry to bother you... Have ever solved the problem? If successful can you guide me?
Thank you so much!
