### ISSUE TITLE
Why you take the abs() and rise to 2 in L_{s}?

### ISSUE THREAD

**Issue by daviduarte** [tianyu0207/RTFM#23]
Hello!

In Equation 6, as shown bellow, you calcule the L_{s} by:

![image](https://user-images.githubusercontent.com/6354107/120891602-db25d280-c5df-11eb-8cb9-0f937e48d276.png)

However, in train.py, you calcule **loss_abn** and **loss_nor** by doing:

```
loss_abn = torch.abs(self.margin - torch.norm(torch.mean(feat_a, dim=1), p=2, dim=1))
loss_nor = torch.norm(torch.mean(feat_n, dim=1), p=2, dim=1)

loss_um = torch.mean((loss_abn + loss_nor) ** 2)
```

Why you used the **torch.abs** and squared **(loss_abn + loss_nor)**? This don't match the equation. Maybe some trick to converge?

Regards!

**Comment by tianyu0207** [comment]
> Hello!
> 
> In Equation 6, as shown bellow, you calcule the L_{s} by:
> 
> ![image](https://user-images.githubusercontent.com/6354107/120891602-db25d280-c5df-11eb-8cb9-0f937e48d276.png)
> 
> However, in train.py, you calcule **loss_abn** and **loss_nor** by doing:
> 
> ```
> loss_abn = torch.abs(self.margin - torch.norm(torch.mean(feat_a, dim=1), p=2, dim=1))
> loss_nor = torch.norm(torch.mean(feat_n, dim=1), p=2, dim=1)
> 
> loss_um = torch.mean((loss_abn + loss_nor) ** 2)
> ```
> 
> Why you used the **torch.abs** and squared **(loss_abn + loss_nor)**? This don't match the equation. Maybe some trick to converge?
> 
> Regards!

Hi Sorry for the late reply. Doing this shows better convergence. it did the same thing as the equation in the paper.

**Comment by wjtan99** [comment]
@tianyu0207 Can you give a reference to why this implementation is the same as Equation (6), or give proof? 
Thanks a lot.

**Comment by coranholmes** [comment]
Hi, I have the same question. Have you got any idea on this?
