### ISSUE TITLE
can you share the pretrained model?

### ISSUE THREAD

**Issue by marsplant** [tianyu0207/RTFM#28]
thanks for your great work!
can you share the pretrained RTFM model of UCF-crime dataset?

**Comment by tianyu0207** [comment]
> thanks for your great work!
> can you share the pretrained RTFM model of UCF-crime dataset?

Hi the pretrained checkpoint is on the Readme Page. Feel free to download.

**Comment by yashika-git** [comment]
Hi @tianyu0207, it seems like the checkpoints' link for the UCF-Crime dataset is disabled.
Could you please look into this?
Thank you!
