### ISSUE TITLE
how to extract i3d features

### ISSUE THREAD

**Issue by ckx506772099** [tianyu0207/RTFM#30]
I see your features‘ shape is N * 10 * 2048，but mix_5c output shape is 1 * 1024 when input is 16 * 224 * 224

**Comment by tianyu0207** [comment]
> I see your features‘ shape is N * 10 * 2048，but mix_5c output shape is 1 * 1024 when input is 16 * 224 * 224

You can simply use this resnet50 I3D to extract the feature.     https://github.com/Tushar-N/pytorch-resnet3d   

This produces 2048 dimensional features. Thanks.
