### ISSUE TITLE
About Feature extraction

### ISSUE THREAD

**Issue by Tsepu** [tianyu0207/RTFM#31]
Hello,

I want to extract C3D features from our dataset. Could you please tell me how did you extract the features.
Especially, i confused with 10 crops. For example if a video has 160 frames, features should 10x4096 with using 16 frames. But your result is 10x10x4096. Could you please explain the 10 crops part?

**Comment by tianyu0207** [comment]
> Hello,
> 
> I want to extract C3D features from our dataset. Could you please tell me how did you extract the features.
> Especially, i confused with 10 crops. For example if a video has 160 frames, features should 10x4096 with using 16 frames. But your result is 10x10x4096. Could you please explain the 10 crops part?

Similar as previous works, we adapt the ten-crop augmentations to each frame. Then we apply C3D or I3D on each augmented frame, resulting in 10 different features for each frame. For your example, the feature will be 10 (10 cropped) * 10 (10 clips) * 4096 (feature dimension) using 16 frames extraction.
