### ISSUE TITLE
code for ucfcrime ground truth

### ISSUE THREAD

**Issue by movingsheep** [tianyu0207/RTFM#32]
Hello,
It seems that you only provide code to make gt for shanghaitech dataset. Could you share the code to make gt for UCF crime dataset? That would be very helpful.

**Comment by tianyu0207** [comment]
> Hello,
> It seems that you only provide code to make gt for shanghaitech dataset. Could you share the code to make gt for UCF crime dataset? That would be very helpful.

Hi the file has uploaded to list folder. Thanks.
