### ISSUE TITLE
About SOTA on XD-Violence

### ISSUE THREAD

**Issue by chengengliu** [tianyu0207/RTFM#35]
Hi guys, thanks for your work. I'm wondering if you guys declare SOTA on XD-Violence? I see from your results, you achieved AP with 77.81 I3D&RGB and you said Wu's [Not only Look, but also Listen](https://github.com/Roc-Ng/XDVioDet) has AP with 75.41. However Wu's paper stated they achieved 78.64 AP and there is no 75.41 appeared in their paper. How did you get 75.41?

**Comment by tianyu0207** [comment]
> Hi guys, thanks for your work. I'm wondering if you guys declare SOTA on XD-Violence? I see from your results, you achieved AP with 77.81 I3D&RGB and you said Wu's [Not only Look, but also Listen](https://github.com/Roc-Ng/XDVioDet) has AP with 75.41. However Wu's paper stated they achieved 78.64 AP and there is no 75.41 appeared in their paper. How did you get 75.41?
![image](https://user-images.githubusercontent.com/19222962/129123940-c980cbac-82e5-4cfb-a0ac-7ce6582aec92.png)

Hi please check the figure 5 from their paper with RGB modality

**Comment by chengengliu** [comment]
> > Hi guys, thanks for your work. I'm wondering if you guys declare SOTA on XD-Violence? I see from your results, you achieved AP with 77.81 I3D&RGB and you said Wu's [Not only Look, but also Listen](https://github.com/Roc-Ng/XDVioDet) has AP with 75.41. However Wu's paper stated they achieved 78.64 AP and there is no 75.41 appeared in their paper. How did you get 75.41?
> > ![image](https://user-images.githubusercontent.com/19222962/129123940-c980cbac-82e5-4cfb-a0ac-7ce6582aec92.png)
> 
> Hi please check the figure 5 from their paper with RGB modality

Thanks, I thought you guys compared with the two-modals approach. Anyway, thanks for your quick response and your brilliant work.
