### ISSUE TITLE
Can you share the checkpoint for shanghaitech dataset?

### ISSUE THREAD

**Issue by nutfly** [tianyu0207/RTFM#37]
I test your model on shanghaitech dataset several times, but the highest AUC is always 96.3x, there is still a big gap from 97.21 given in the paper.
Could you please share the checkpoint for shanghaitech dataset? thanks a lot

**Comment by DungVo1507** [comment]
Hello @nutfly 
I am also using this model on ShanghaiTech dataset but I am getting CUDA out of memory error. I tried reducing batch size = 16 and still error. Can you guide me on how you apply RTFM?
Thank you so much!
