### ISSUE TITLE
After obtaining the final temporal feature representation X

### ISSUE THREAD

**Issue by DungVo1507** [tianyu0207/RTFM#39]
Thanks for viewing my issue, @tianyu0207 
I have 4 questions that I hope you can explain:
1. After obtaining X, the snippets have been divided into 2 groups normal and abnormal, right?
2. In the Select Top-k snippets stage, do you select k snippets from both the normal and the abnormal groups, or will each group select k snippets?
3. Assuming k = 3, in case a video has less than 3 abnormal or normal snippets, how will RTFM choose?
4. When the input is normal video, how will the RTFM-enabled Snippet Classifier Learning stage classify?

**Comment by tianyu0207** [comment]
> Thanks for viewing my issue, @tianyu0207
> I have 4 questions that I hope you can explain:
> 
> 1. After obtaining X, the snippets have been divided into 2 groups normal and abnormal, right?
> 2. In the Select Top-k snippets stage, do you select k snippets from both the normal and the abnormal groups, or will each group select k snippets?
> 3. Assuming k = 3, in case a video has less than 3 abnormal or normal snippets, how will RTFM choose?
> 4. When the input is normal video, how will the RTFM-enabled Snippet Classifier Learning stage classify?

Hi,

1. After obtaining the video, the snippets will be divide into 32 segments. Each segment will be a 2048 feature vector. We don't change the order of the snippets. 
2.  We select the snippets with top-k magnitude from each normal and abnormal video to obtain hard normals and pseudo abnormals.  
3. Assuming k = 3, in case a video has less than 3 abnormal or normal snippets, RTFM will choose the top-3 as well. This may include some of the false snippets. But in our experiment, we notice our approach is robust enough to handle this. 
4. Each batch will have the same number of normal and abnormal videos. Hence, there will be the equal number of samples from two classes during the classifier learning stage.

**Comment by DungVo1507** [comment]
Thanks for your reply, @tianyu0207 
After reading your response I drew RTFM according to my thoughts, please check it out and give me a comment.
![RTFM](https://user-images.githubusercontent.com/67866442/130440476-74e5e7b6-71a2-4eec-810b-d76b68f10673.png)

Besides that, I have two other questions for you to answer:
1. In my opinion k snippets with the highest feature magnitude in a normal video are still normals, so those snippets are called hard normals right? and k snippets with the highest feature magnitude in an abnormal video then will be abnormals, why is there the concept of "pseudo abnormals"? Can you explain the concept of "hard normals" and "pseudo abnormals" to me?
2. Suppose I have 50 batches, 25 normal videos, and 50 abnormal videos, then from the 26th batch to the 50th batch, how will the normal video input be taken?

**Comment by tianyu0207** [comment]
> 1. pseudo

Hard normal will be the snippets that are similar to abnormal events. Pseudo abnormal means there may be snippets that are not actual abnormal because we try to select abnormal instances from the abnormal bag. There are no snippet-level labels.  I don't quite understand your second question. Sorry..

**Comment by DungVo1507** [comment]
Thanks very much, @tianyu0207 
Can you give me a comment on the RTFM drawing in my mind?
![RTFM](https://user-images.githubusercontent.com/67866442/130440476-74e5e7b6-71a2-4eec-810b-d76b68f10673.png)
I don't know if my thinking is correct?

Grateful to you!

**Comment by DungVo1507** [comment]
Thank you so much @tianyu0207,
The second question means: you say each batch will have the same number of normal and abnormal videos, so the number of normal and abnormal videos in the dataset should be equal right?
If each batch will have the same number of normal and abnormal videos, is the drawing of how RTFM works I attached below correct?
![RTFM](https://user-images.githubusercontent.com/67866442/130577115-47e8977e-0913-46da-a74b-a8d0841aa1ef.png)

I hope you will reply!
Appreciate your support!

**Comment by tianyu0207** [comment]
> Thank you so much @tianyu0207,
> The second question means: you say each batch will have the same number of normal and abnormal videos, so the number of normal and abnormal videos in the dataset should be equal right?
> If each batch will have the same number of normal and abnormal videos, is the drawing of how RTFM works I attached below correct?
> ![RTFM](https://user-images.githubusercontent.com/67866442/130577115-47e8977e-0913-46da-a74b-a8d0841aa1ef.png)
> 
> I hope you will reply!
> Appreciate your support!

each batch has the same number of normal and abnormal videos does not necessarily mean you have the equal number of videos in the dataset. you just sample evenly for each batch. 

Hi I reckon Your figure is correct.
