### ISSUE TITLE
Training and testing in ShanghaiTech Campus dataset

### ISSUE THREAD

**Issue by DivineZeng** [tianyu0207/RTFM#4]
Hi tianyu! 
Thank you for your perfect job. I want to know why in your method, the split of the training and test data sets is not the same as the original. In addition, when I ran the test function, I found that starting from video 43, gt is always Flase?

**Comment by tianyu0207** [comment]
This is the weakly supervised setup used in 'Graph Convolutional Label Noise Cleaner: Train a Plug-and-play Action Classifier for Anomaly Detection'. We follow the same setup as their work.

**Comment by tianyu0207** [comment]
> Hi tianyu!
> Thank you for your perfect job. I want to know why in your method, the split of the training and test data sets is not the same as the original. In addition, when I ran the test function, I found that starting from video 43, gt is always Flase?

This is the weakly supervised setup used in 'Graph Convolutional Label Noise Cleaner: Train a Plug-and-play Action Classifier for Anomaly Detection'. We follow the same setup as their work.
