### ISSUE TITLE
Detail for temporal number of  i3d feature 

### ISSUE THREAD

**Issue by sdjsngs** [tianyu0207/RTFM#40]
Hi, first of all, congratulations on the successful acceptance of your paper! 
After i download the feature you have released  and check the feature, while the temporal number of the feature is different as the pervious work released.  
For example, one video with 17 frames, the previous work would  ignore the last group frames (less than 16 frames) and obtain 1 feature, while the feature data of yours is 2 features, can you say some detail of  temporal operation in feature extractor?   

I also see the code you have write in make_gt.py , and the temporal length of gt is based on feature numbers and this would make you have   longer gt  than the origin dataset.

**Comment by tianyu0207** [comment]
> Hi, first of all, congratulations on the successful acceptance of your paper!
> After i download the feature you have released and check the feature, while the temporal number of the feature is different as the pervious work released.
> For example, one video with 17 frames, the previous work would ignore the last group frames (less than 16 frames) and obtain 1 feature, while the feature data of yours is 2 features, can you say some detail of temporal operation in feature extractor?
> 
> I also see the code you have write in make_gt.py , and the temporal length of gt is based on feature numbers and this would make you have longer gt than the origin dataset.

Hi, 
I sample the last frame 16 times for your 17 frames example. The feature will then be 2 features.  For make_gt.py, the gt will inherit the label of the last frame. For your 17 frames example, if the last frame is normal then the ground truth for that feature will be 16 normal, if it's abnormal, then the frame will be 16 abnormal at the end. This will somehow has a bit longer gt than the original dataset. But compared with methods that skip the last few frames, they will have a small number of gt than the original dataset. So I guess both evaluations have problems.....
