### ISSUE TITLE
Visualizer function

### ISSUE THREAD

**Issue by DungVo1507** [tianyu0207/RTFM#42]
Hello @tianyu0207,
In the main.py file there is a command like this: `viz = Visualizer(env='shanghai tech 10 crop', use_incoming_socket=False)`
I found the Visualizer function in the utils.py file but I still don't understand where the parameter 'shanghai tech 10 crop' comes from?
and am I wrong in assuming the step variable has a value of 5000?
Thanks for your help!

**Comment by tianyu0207** [comment]
> Hello @tianyu0207,
> In the main.py file there is a command like this: `viz = Visualizer(env='shanghai tech 10 crop', use_incoming_socket=False)`
> I found the Visualizer function in the utils.py file but I still don't understand where the parameter 'shanghai tech 10 crop' comes from?
> and am I wrong in assuming the step variable has a value of 5000?
> Thanks for your help!

Hi This is a Visualizer funtion, the  env is the name of your experiment. You should install the visdom by pip and then run python -m visdom.server on your terminal.
