### ISSUE TITLE
Ground truth of XD-Violence

### ISSUE THREAD

**Issue by DungVo1507** [tianyu0207/RTFM#44]
The AP result of the Violence dataset I got was only 0.15.
I fixed a few places when implementing RTFM on XD-Violence:

- Change `rec_auc` to `ap = average_precision_score(list(gt), pred, pos_label=1)` in test_10crop.py
- From first index to the 2046th index are normal, the rest are abnormal, so I edited dataset.py like this:
```
def _parse_list(self):
        self.list = list(open(self.rgb_list_file))
        if self.test_mode is False:
            if self.is_normal:
                self.list = self.list[:2046]
            else:
                self.list = self.list[2046:]
```

- And I fixed model.py since XD-Violence uses 5 crops:
```
normal_features = features[0:self.batch_size*5]
normal_scores = scores[0:self.batch_size]

abnormal_features = features[self.batch_size*5:]
abnormal_scores = scores[self.batch_size:]
```

I think maybe my XD-Violence's ground truth isn't right?
Where do you think I am going wrong and could you please give me the ground truth of XD-Violence?

Thank you so much @tianyu0207

**Comment by coranholmes** [comment]
Have you managed to improve your AP on violence dataset?
