### ISSUE TITLE
How to 10 crops augmentation

### ISSUE THREAD

**Issue by DungVo1507** [tianyu0207/RTFM#46]
Hi @tianyu0207,

I have extracted a 3D feature on our dataset, the feature file has a shape (k, 2048) where k equals the number of frames of the video divided by 16.

Can you show me how to do 10 crops augmentation per video, from there I will combine 10 feature files together to create shapes (10,k, 2048)?

Thank you very much!

**Comment by tianyu0207** [comment]
> Hi @tianyu0207,
> 
> I have extracted a 3D feature on our dataset, the feature file has a shape (k, 2048) where k equals the number of frames of the video divided by 16.
> 
> Can you show me how to do 10 crops augmentation per video, from there I will combine 10 feature files together to create shapes (10,k, 2048)?
> 
> Thank you very much!

Hi you can use PyTorch tencrop official library.
