### ISSUE TITLE
How is the input dimension of the I3D feature vector generated?

### ISSUE THREAD

**Issue by Shashank56** [tianyu0207/RTFM#5]
I have doubt regarding the dimension required of the input discussed in the paper. It is said that the input is a T*2048 feature vector for a given video. And it also said that T is taken as 32 in implementation details. 

Does this mean, for any given video, we need to divide it into 32 parts (no matter the no.of frames) and find 1*2048 vector for each part?

**Comment by tianyu0207** [comment]
Yes.  For a batch of videos, we evenly divide each video into 32 parts and form a Batch * 32 * 2048 feature vector for this batch.

**Comment by tianyu0207** [comment]
> I have doubt regarding the dimension required of the input discussed in the paper. It is said that the input is a T*2048 feature vector for a given video. And it also said that T is taken as 32 in implementation details.
> 
> Does this mean, for any given video, we need to divide it into 32 parts (no matter the no.of frames) and find 1*2048 vector for each part?

Yes. For a batch of videos, we evenly divide each video into 32 parts and form a Batch * 32 * 2048 feature vector for this batch.
