### ISSUE TITLE
提取ShanghaiTech数据集I3D特征

### ISSUE THREAD

**Issue by Holdwsq** [tianyu0207/RTFM#53]
​​        ​        您好，很有益的工作，在我的科研工作中有很大的帮助！但在提取ShanghaiTech数据集I3D特征的过程中遇见了一些难题，提取出来的特征与您公开的I3D特征有些许差异，所以想请教您几个问题：

问题1：计算clip的数量

​        ​        是否将一个视频的帧按照每16帧一个clip进行划分，针对最后一个clip就有两种情况：

​        ​        情况1：最后一个clip不满16帧，是不是复制最后一个视频帧，使其满16帧

​        ​        情况2：最后一个clip刚好16帧，我看您提取的ShanghaiTech数据集I3D特征是新增一个clip，然后该clip中的视频帧都是复制最后一帧（比如：视频01_047，总帧数为1056，刚好被16整除，产生66个clip，您提取的i3d特征维度却是(67, 10, 2048)）；

问题2：关于resize与TenCrop视频帧的大小

​​        ​        在提取ShanghaiTech数据集I3D特征时，在Resize与TenCrop视频帧时设置的大小是多少呢?

​​        ​        下面是我设置：

```python
    # resize图像大小
    gtransforms.GroupResize((224, 224)),
    # 裁剪图像的方式
    gtransforms.GroupTenCrop(224),
```

问题3：mean和std的选择

​​        ​        在提取ShanghaiTech数据集I3D特征时，怎么设置数据集的均值mean和std的呢？

​​        ​        请问您使用下面的设置么？

```python
    mean = [114.75, 114.75, 114.75]
    std = [57.375, 57.375, 57.375]
```

期盼您的回复，谢谢！

**Comment by tianyu0207** [comment]
> ​​ ​ 您好，很有益的工作，在我的科研工作中有很大的帮助！但在提取ShanghaiTech数据集I3D特征的过程中遇见了一些难题，提取出来的特征与您公开的I3D特征有些许差异，所以想请教您几个问题：
> 
> 问题1：计算clip的数量
> 
> ​ ​ 是否将一个视频的帧按照每16帧一个clip进行划分，针对最后一个clip就有两种情况：
> 
> ​ ​ 情况1：最后一个clip不满16帧，是不是复制最后一个视频帧，使其满16帧
> 
> ​ ​ 情况2：最后一个clip刚好16帧，我看您提取的ShanghaiTech数据集I3D特征是新增一个clip，然后该clip中的视频帧都是复制最后一帧（比如：视频01_047，总帧数为1056，刚好被16整除，产生66个clip，您提取的i3d特征维度却是(67, 10, 2048)）；
> 
> 问题2：关于resize与TenCrop视频帧的大小
> 
> ​​ ​ 在提取ShanghaiTech数据集I3D特征时，在Resize与TenCrop视频帧时设置的大小是多少呢?
> 
> ​​ ​ 下面是我设置：
> 
> ```python
>     # resize图像大小
>     gtransforms.GroupResize((224, 224)),
>     # 裁剪图像的方式
>     gtransforms.GroupTenCrop(224),
> ```
> 
> 问题3：mean和std的选择
> 
> ​​ ​ 在提取ShanghaiTech数据集I3D特征时，怎么设置数据集的均值mean和std的呢？
> 
> ​​ ​ 请问您使用下面的设置么？
> 
> ```python
>     mean = [114.75, 114.75, 114.75]
>     std = [57.375, 57.375, 57.375]
> ```
> 
> 期盼您的回复，谢谢！

你好 
问题1： 情况1是这样的
情况2 正常能被16整除应该是可以的不需要复制 可能我在把视频分解的帧率有问题 所以会出现67 个clip 正常情况下 如果您提取的帧是正常的 能被16 整除就刚好是clip的数量 不需要复制

问题2: 我使用的应该是 
 # resize图像大小
    gtransforms.GroupResize((256, 256)),
    # 裁剪图像的方式
    gtransforms.GroupTenCrop(224),

使用的是kinetic默认的mean 和std   应该就是您提供的这个
mean = [114.75, 114.75, 114.75]
std = [57.375, 57.375, 57.375]

**Comment by NoPlenty** [comment]
你好！我用作者给的特征提取参考代码遇到了很多问题，请问您介意分享一下你的i3d特征提取源码吗？不胜感激！

**Comment by yuyuer-dev** [comment]
您在提取特征时步长设置的是几？为什么这样设置？步长设置有什么规则吗？
