### ISSUE TITLE
Retrain the method in using I3D features

### ISSUE THREAD

**Issue by DungVo1507** [tianyu0207/RTFM#54]
Hi @tianyu0207,
May I ask when you retrain the method of Sultani et al using I3D features, did you use ten-crop augmentation?
Thank you so much!

**Comment by tianyu0207** [comment]
> Hi @tianyu0207, May I ask when you retrain the method of Sultani et al using I3D features, did you use ten-crop augmentation? Thank you so much!

Hi the ablation is training using the same ten-crop augmented features
