### ISSUE TITLE
Using custom dataset

### ISSUE THREAD

**Issue by ro1406** [tianyu0207/RTFM#56]
Hi! Hope you're doing well.

I have been able to run the code successfully on the given features, and wanted to try it on another dataset. 
 I was unable to figure out how to use the repo you had mentioned in other issues to extract the features, hence I used this repo (https://github.com/v-iashin/video_features) to extract the i3d features and then used the pytorch inbuilt tencrop function while loading the dataset.

Ten crop done by:
transformss = transforms.Compose([
         transforms.ToPILImage(),
         transforms.TenCrop(2048),
         transforms.Lambda(lambda crops: torch.stack([transforms.ToTensor()(crop) for crop in crops])) 
         ])
Using any number other than 2048 in TenCrop, such as 31, gives an error "Given groups=1, weight of size [512, 2048, 3], expected input[31, 31, 10] to have 2048 channels, but got 31 channels instead"

Moreover, I keep getting errors in size mismatch while trying to run it. "shape '[1, 2048, 10, 2048]' is invalid for input of size 3276800"  from this line "abnormal_features = abnormal_features.view(n_size, ncrops, t, f) " Line 239 in model.py

Additionally, I wanted to ask how exactly the results of the ground truth files are structured since it seems to just be a single binary array?

I would appreciate any help and guidance you could provide on the above.
Thanks & Regards

**Comment by ro1406** [comment]
> Hey bro, I have the same problem as you. Did you find any solution??

Hey, unfortunately, none so far. I would appreciate it if you could share if you found a solution (even if its a partial one) if you do. I shall post here if i do find a solution

**Comment by tianyu0207** [comment]
> Hi! Hope you're doing well.
> 
> I have been able to run the code successfully on the given features, and wanted to try it on another dataset. I was unable to figure out how to use the repo you had mentioned in other issues to extract the features, hence I used this repo (https://github.com/v-iashin/video_features) to extract the i3d features and then used the pytorch inbuilt tencrop function while loading the dataset.
> 
> Ten crop done by: transformss = transforms.Compose([ transforms.ToPILImage(), transforms.TenCrop(2048), transforms.Lambda(lambda crops: torch.stack([transforms.ToTensor()(crop) for crop in crops])) ]) Using any number other than 2048 in TenCrop, such as 31, gives an error "Given groups=1, weight of size [512, 2048, 3], expected input[31, 31, 10] to have 2048 channels, but got 31 channels instead"
> 
> Moreover, I keep getting errors in size mismatch while trying to run it. "shape '[1, 2048, 10, 2048]' is invalid for input of size 3276800" from this line "abnormal_features = abnormal_features.view(n_size, ncrops, t, f) " Line 239 in model.py
> 
> Additionally, I wanted to ask how exactly the results of the ground truth files are structured since it seems to just be a single binary array?
> 
> I would appreciate any help and guidance you could provide on the above. Thanks & Regards

Hi please mike sure the input shape is (batch_size, 10, t, 2048), where t is the number of the clips of a video.

ground truth are structured as single binary array followed the i3d files in list directory, where each binary value represents if its normal or not

**Comment by ro1406** [comment]
Thank 

> > Hi! Hope you're doing well.
> > I have been able to run the code successfully on the given features, and wanted to try it on another dataset. I was unable to figure out how to use the repo you had mentioned in other issues to extract the features, hence I used this repo (https://github.com/v-iashin/video_features) to extract the i3d features and then used the pytorch inbuilt tencrop function while loading the dataset.
> > Ten crop done by: transformss = transforms.Compose([ transforms.ToPILImage(), transforms.TenCrop(2048), transforms.Lambda(lambda crops: torch.stack([transforms.ToTensor()(crop) for crop in crops])) ]) Using any number other than 2048 in TenCrop, such as 31, gives an error "Given groups=1, weight of size [512, 2048, 3], expected input[31, 31, 10] to have 2048 channels, but got 31 channels instead"
> > Moreover, I keep getting errors in size mismatch while trying to run it. "shape '[1, 2048, 10, 2048]' is invalid for input of size 3276800" from this line "abnormal_features = abnormal_features.view(n_size, ncrops, t, f) " Line 239 in model.py
> > Additionally, I wanted to ask how exactly the results of the ground truth files are structured since it seems to just be a single binary array?
> > I would appreciate any help and guidance you could provide on the above. Thanks & Regards
> 
> Hi please mike sure the input shape is (batch_size, 10, t, 2048), where t is the number of the clips of a video.
> 
> ground truth are structured as single binary array followed the i3d files in list directory, where each binary value represents if its normal or not

Thank you for your reply! I managed to get it to work with a custom dataset. Appreciate the timely help!

**Comment by ahmedwael19** [comment]
Hi @ro1406 
how did you manage to prepare the ground truth for the custom dataset?
I'd really appreciate your help.

**Comment by ro1406** [comment]
> Hi @ro1406 how did you manage to prepare the ground truth for the custom dataset? I'd really appreciate your help.

Hi! Well i really just followed the previous comment:
"ground truth are structured as single binary array followed the i3d files in list directory, where each binary value represents if its normal or not"

For each file in the directory, for each frame, just put a 1 if the frame is normal, and 0 if the frame is abnormal. Save that array and use it as the ground truth file
