### ISSUE TITLE
Corrupted trained I3D features on UCF-crime dataset

### ISSUE THREAD

**Issue by lts427** [tianyu0207/RTFM#57]
Wonderful work! 

Recently, I found that the pre-extracted I3D features are corrupted in both google-drive and onedrive links. So I would appreciate it if you can upload the correct files.

Thank you and looking forward to your reply.

**Comment by tianyu0207** [comment]
> Wonderful work!
> 
> Recently, I found that the pre-extracted I3D features are corrupted in both google-drive and onedrive links. So I would appreciate it if you can upload the correct files.
> 
> Thank you and looking forward to your reply.

Hi the code is fine on my side. Could you double check?

**Comment by lts427** [comment]
My point is that the pre-extracted I3D features downloaded from google-drive links seem not correct. Since the number of training sample is 1610 in your given list, but the downloaded features only contain around 600 samples. So I would appreciate it if you can check this issue. Thank you.

**Comment by tianyu0207** [comment]
> 

Oh Cool. I will re-upload the features. Thanks.

**Comment by lts427** [comment]
Thank you. Currently, I found that the original google-drive link did not work. You may need to update the link when the features have been re-uploaded.

**Comment by tianyu0207** [comment]
> Thank you. Currently, I found that the original google-drive link did not work. You may need to update the link when the features have been re-uploaded.

Hi, the google drive features have been updated now. Thanks.
