### ISSUE TITLE
having trouble downloading the features

### ISSUE THREAD

**Issue by windwen** [tianyu0207/RTFM#58]
I'm having trouble downloading the UCF-Crime train I3d features. Is there anyone else download it and upload it to another cloud disk, like Baidu cloud disk.

**Comment by tianyu0207** [comment]
> I'm having trouble downloading the UCF-Crime train I3d features. Is there anyone else download it and upload it to another cloud disk, like Baidu cloud disk.

Hi, I have fixed the link on google drive. Should be fine now
