### ISSUE TITLE
train request

### ISSUE THREAD

**Issue by carolchenyx** [tianyu0207/RTFM#6]
Dear all, thanks for your excellent work. There is a problem when I ran the main.py file. It needs a file called shanghai-i3d-test-10crop-figure.list. I would like to know how can I get this file? Thank you.

**Comment by carolchenyx** [comment]
Another problem after changing the shanghai-i3d-test-10crop-figure.list to  shanghai-i3d-test-10crop.list. The code error is shown below:
##########################################################3
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hkuit104/anaconda3/envs/adCVPR18/lib/python3.7/site-packages/visdom/__init__.py", line 711, in _send
    data=json.dumps(msg),
  File "/home/hkuit104/anaconda3/envs/adCVPR18/lib/python3.7/site-packages/visdom/__init__.py", line 677, in _handle_post
    r = self.session.post(url, data=data)
  File "/home/hkuit104/anaconda3/envs/adCVPR18/lib/python3.7/site-packages/requests/sessions.py", line 581, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/hkuit104/anaconda3/envs/adCVPR18/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/hkuit104/anaconda3/envs/adCVPR18/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/hkuit104/anaconda3/envs/adCVPR18/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /update (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f37002d76a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
  1%|▎                                       | 99/15000 [00:22<48:34,  5.11it/s]
#############################################################33

**Comment by tianyu0207** [comment]
> Another problem after changing the shanghai-i3d-test-10crop-figure.list to shanghai-i3d-test-10crop.list. The code error is shown below:
> ##########################################################3
> During handling of the above exception, another exception occurred:
> Traceback (most recent call last):
> File "/home/hkuit104/anaconda3/envs/adCVPR18/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
> timeout=timeout
> File "/home/hkuit104/anaconda3/envs/adCVPR18/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
> _stacktrace=sys.exc_info()[2])
> File "/home/hkuit104/anaconda3/envs/adCVPR18/lib/python3.7/site-packages/urllib3/util/retry.py", line 399, in increment
> raise MaxRetryError(_pool, url, error or ResponseError(cause))
> urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /update (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f37002d76a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "/home/hkuit104/anaconda3/envs/adCVPR18/lib/python3.7/site-packages/visdom/**init**.py", line 711, in _send
> data=json.dumps(msg),
> File "/home/hkuit104/anaconda3/envs/adCVPR18/lib/python3.7/site-packages/visdom/**init**.py", line 677, in _handle_post
> r = self.session.post(url, data=data)
> File "/home/hkuit104/anaconda3/envs/adCVPR18/lib/python3.7/site-packages/requests/sessions.py", line 581, in post
> return self.request('POST', url, data=data, json=json, **kwargs)
> File "/home/hkuit104/anaconda3/envs/adCVPR18/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
> resp = self.send(prep, **send_kwargs)
> File "/home/hkuit104/anaconda3/envs/adCVPR18/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
> r = adapter.send(request, **kwargs)
> File "/home/hkuit104/anaconda3/envs/adCVPR18/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
> raise ConnectionError(e, request=request)
> requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /update (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f37002d76a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
> 1%|▎ | 99/15000 [00:22<48:34, 5.11it/s]
> #############################################################33

hi, this seems the issue of visdom. Please open the visdom server first before running the experiment.

**Comment by carolchenyx** [comment]
Thanks Yu Tian. I salved it by running visdom.

Yu Tian ***@***.***> 于2021年4月14日周三 下午5:47写道：
