### ISSUE TITLE
One Drive UCF-Crime Files Downloading Issue

### ISSUE THREAD

**Issue by UmmarHassan96** [tianyu0207/RTFM#64]
I am unable to download onedrive files as many of them are corrupted and they are not downloading. Google Drive files are downloadable and are working but files which are in onedrive link are absent in Google Drive link.

**Comment by tianyu0207** [comment]
> in

Hi Thanks for your interest. The download link has been fixed and now all files should be available in Google Drive and Onedrive.

**Comment by zuble** [comment]
hi @tianyu0207  :)
the links in onedrive are down again.
the test features in google drive are incomplete
could you update the links ? 
many thanks

**Comment by JonathanFlores2503** [comment]
Hello @zuble, were you able to download the missing features of UCF-Crime

**Comment by zuble** [comment]
> Hello @zuble, were you able to download the missing features of UCF-Crime

unfortunately no
