### ISSUE TITLE
关于test_dataloader的label

### ISSUE THREAD

**Issue by Apollo-asleep** [tianyu0207/RTFM#65]
您好，有如下两个问题
1.在./list/make_gt_sh,py line 48
ground_annotation = np.load(os.path.join(temporal_root, gt_file))
这一行是从[temporal_root = 'test_frame_mask/']中取出数据，但是没有开源test_frame_mask文件，是在其他repo有吗
2.同样文件在line31，num_frame = features.shape[0] * 16，这一行是什么原因要*16呢

**Comment by tianyu0207** [comment]
> 您好，有如下两个问题 1.在./list/make_gt_sh,py line 48 ground_annotation = np.load(os.path.join(temporal_root, gt_file)) 这一行是从[temporal_root = 'test_frame_mask/']中取出数据，但是没有开源test_frame_mask文件，是在其他repo有吗 2.同样文件在line31，num_frame = features.shape[0] * 16，这一行是什么原因要*16呢

1. 你好 test_frame_mask 文件里面是annotation 文件 这个可以在shanghaitech 和UCF的官方网站下载 

2. 因为每个clip含有16帧frame 所以统计总frame number的时候需要乘上16
