### ISSUE TITLE
Regarding I3D Network

### ISSUE THREAD

**Issue by Shashank56** [tianyu0207/RTFM#7]
While extracting the features using an I3D network with resnet50 backbone, which pretrained model did you use and did you finetune it with the dataset before extracting features?

**Comment by tianyu0207** [comment]
> While extracting the features using an I3D network with resnet50 backbone, which pretrained model did you use and did you finetune it with the dataset before extracting features?

You can simply use this repo https://github.com/Tushar-N/pytorch-resnet3d. 
I did not finetune it with the dataset.
