### ISSUE TITLE
About the ground truth of UCF-crime dataset

### ISSUE THREAD

**Issue by coranholmes** [tianyu0207/RTFM#73]
你好，关于UCF-Crime原数据集只提供了video级别的标注，请问frame级别的标注去哪里获取呢？我看了`list/make_gt_ucf.py`里的代码，我看读取了一些mat文件，请问这些文件去哪里下载呢？

**Comment by tianyu0207** [comment]
> 你好，关于UCF-Crime原数据集只提供了video级别的标注，请问frame级别的标注去哪里获取呢？我看了`list/make_gt_ucf.py`里的代码，我看读取了一些mat文件，请问这些文件去哪里下载呢？

hi, the mat files have been uploaded. Thanks for your interest.
