### ISSUE TITLE
make_gt_ucf.py

### ISSUE THREAD

**Issue by C0NGTRI123** [tianyu0207/RTFM#83]
Hello when I running make_gt_ucf.py. I see so lot path of files not exists in folder list to train ucf-crime. Can you share how to fix this, thank you very much
![Screenshot from 2022-09-27 17-07-01](https://user-images.githubusercontent.com/45964648/192498333-3f217d65-5c92-4e8e-88c7-2c5e27c63852.png)

**Comment by dukocuk** [comment]
> Hello when I running make_gt_ucf.py. I see so lot path of files not exists in folder list to train ucf-crime. Can you share how to fix this, thank you very much ![Screenshot from 2022-09-27 17-07-01](https://user-images.githubusercontent.com/45964648/192498333-3f217d65-5c92-4e8e-88c7-2c5e27c63852.png)

did you find a solution?

**Comment by tianyu0207** [comment]
> Hello when I running make_gt_ucf.py. I see so lot path of files not exists in folder list to train ucf-crime. Can you share how to fix this, thank you very much ![Screenshot from 2022-09-27 17-07-01](https://user-images.githubusercontent.com/45964648/192498333-3f217d65-5c92-4e8e-88c7-2c5e27c63852.png)

The file has been uploaded. Thanks for your interest.
