### ISSUE TITLE
Error in test_10crop.py while training with C3D features

### ISSUE THREAD

**Issue by Yggdrasil09** [tianyu0207/RTFM#9]
I'm training on the UCF Crime dataset based on the C3D features. While running main.py, initially test.py is called and the size of the `dataloader.dataset` argument that is passed is `(266, 32, 4096)`  and this is resulting in error. I think this is because the code is iterating on the dataloader and each item doesn't have 4 dimensions to permute.

`Traceback (most recent call last):
  File "main.py", line 45, in <module>
    auc = test(test_loader, model, args, viz, device)
  File "/home/yggdrasil/WorkingDirectory/FinalYearProject/RTFM/test_10crop.py", line 13, in test
    input = input.permute(0,2,1,3)
RuntimeError: number of dims don't match in permute`

BTW all my features are of dimension `1*32*4096` per video.  And the batch size argument passed in option.py is 32. What do I need to do to solve this?

**Comment by tianyu0207** [comment]
> I'm training on the UCF Crime dataset based on the C3D features. While running main.py, initially test.py is called and the size of the `dataloader.dataset` argument that is passed is `(266, 32, 4096)` and this is resulting in error. I think this is because the code is iterating on the dataloader and each item doesn't have 4 dimensions to permute.
> 
> `Traceback (most recent call last): File "main.py", line 45, in <module> auc = test(test_loader, model, args, viz, device) File "/home/yggdrasil/WorkingDirectory/FinalYearProject/RTFM/test_10crop.py", line 13, in test input = input.permute(0,2,1,3) RuntimeError: number of dims don't match in permute`
> 
> BTW all my features are of dimension `1*32*4096` per video. And the batch size argument passed in option.py is 32. What do I need to do to solve this?

Please use the 10 crop I3D features for UCF-Crime. Then you will have something like (266, 10, 32, 4096).
