### ISSUE TITLE
How to implement inference code?

### ISSUE THREAD

**Issue by yunseokddi** [tianyu0207/RTFM#90]
Hello bro, Thank for your paper and codes.
I'm developing inference code, But I have a question.
If I running inference code, Inference dataset is extracted I3D too? or reshaping to (frame)*(10)*(2048)?
Thx!

**Comment by ro1406** [comment]
> Hello bro, Thank for your paper and codes. I'm developing inference code, But I have a question. If I running inference code, Inference dataset is extracted I3D too? or reshaping to (frame)_(10)_(2048)? Thx!

Hi! Just wanted to ask if you were able to develop the inference code and if you could either share it, or guide me on how to do the same? Thank you!
